name: Daily Submodule Update Check

on:
  schedule:
    - cron: "0 0 * * *"  # every day at 00:00 UTC
  workflow_dispatch:       # allows manual run too

jobs:
  update-submodules:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout utils repo (with submodules)
        uses: actions/checkout@v4
        with:
          submodules: true
          token: ${{ secrets.PAT }}

      - name: Configure Git
        run: |
          git config user.name "mikkurogue"
          git config user.email "michael.lindemans@outlook.com"

      - name: Update submodules and get updated list
        id: update_submodules
        run: |
          # Update each submodule to latest master
          git submodule foreach 'git fetch origin master && git checkout FETCH_HEAD'
          
          # Stage the submodule changes
          git add .
          
          # Check if there are any changes
          if git diff --cached --quiet; then
            echo "No submodule updates"
            echo "updated_submodules=" >> $GITHUB_OUTPUT
          else
            # List submodules that actually changed
            UPDATED_SUBMODULES=$(git diff --cached --name-only | grep -E '^[^/]+/' | cut -d'/' -f1 | sort -u | tr '\n' ' ' || true)
            echo "updated_submodules=$UPDATED_SUBMODULES" >> $GITHUB_OUTPUT
            echo "Updated submodules: $UPDATED_SUBMODULES"
          fi

      - name: Commit and push if submodules changed
        if: steps.update_submodules.outputs.updated_submodules != ''
        run: |
          UPDATED_LIST=$(echo "${{ steps.update_submodules.outputs.updated_submodules }}" | tr ' ' ',' | sed 's/,$//')
          git commit -m "chore: update submodules: $UPDATED_LIST [$(date -u +'%Y-%m-%d %H:%M:%S UTC')]"
          git push origin master
